adding logos to pre-footer
marzeelabs/portuguese_women_tech pull request #34
Opened 2017-02-27 10:37 UTC by pdsdesign

2017-03-02 11:58 UTC, lmcorreia requested changes

2017-03-02 11:58 UTC, lmcorreia commented on themes/mz_hugo/layouts/partials/footer.html
> +        <img src="images/partners/fes-logo.svg">
You need an absolute path or else it won't work on all pages. Check for example: https://58b80755a7e2d26a2eeff88b--pwit-cms.netlify.com/mission/

You need on all these something like:
`<img src="/images/partners/fes-logo.svg">`

2017-03-06 09:08 UTC, nunoveloso commented
@lmcorreia @pdsdesign how's this coming along? Can merge?

2017-03-06 11:35 UTC, lmcorreia approved these changes

2017-03-06 11:35 UTC, merged